name: boostsecurity.io

on:
    workflow_dispatch:
    push:
        branches:
            - main
    
jobs:
     snyk-dev:
         name: snyk-dev
         runs-on: ubuntu-latest
         steps:
             - name: Checkout
               uses: actions/checkout@v3
             - name: Run Snyk
               uses: boostsecurityio/boostsec-scanner-github@v4
               env:
                   SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
               with:
                   api_endpoint: https://api.dev.boostsec.io
                   api_token: ${{ secrets.BOOST_API_TOKEN }}
                   registry_module: boostsecurityio/snyk-test
     snyk-prod:
         name: snyk-prod
         runs-on: ubuntu-latest
         steps:
             - name: Checkout
               uses: actions/checkout@v3
             - name: Run Snyk
               uses: boostsecurityio/boostsec-scanner-github@v4
               env:
                   SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
               with:
                   api_token: ${{ secrets.BOOST_PROD_API_TOKEN }}
                   registry_module: boostsecurityio/snyk-test
 
